server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html/app/public;
    charset utf-8;

    # Log files
    access_log /var/log/nginx/project_access.log;
    error_log /var/log/nginx/project_error.log;

    # Handle static files
    location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml)$ {
        access_log        off;
        log_not_found     off;
        expires           360d;
    }

    # Main location block
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass PHP scripts to the php_fpm service
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # The service name 'php_fpm' is used here
        fastcgi_pass php_fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}